"""
-------------------------------------------------------------------------------
Project: Plotting Script for High-Altitude Balloon Mission Data

File:    plot.py

Purpose: Parses and plots CCSDS data files generated by the flight-state-machine.py script.
         Plots time-series data for various sensors (temperature, acceleration, etc.).
         Allows filtering of data by timestamp range.


Logic:   1. Reads all .ccsds files in the specified data folder.
         2. Unpacks the binary data according to the defined payload format.
         3. Stores the data in structured lists for each sensor type.
         4. Generates scatter plots for each sensor type over time.
         5. Saves the plots as PNG files in a "graphs" folder.
         6. Creates an index.html file in the "graphs" folder to view all plots in a web browser.
-------------------------------------------------------------------------------
Author:  James Scott
Date:    February 2026
-------------------------------------------------------------------------------
"""

import struct
import os
import glob
import sys
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime

import struct
import os
import glob
import sys
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime

# --- CONFIGURATION ---
PAYLOAD_FORMAT = ">Iffff fff fff fff fff fff fff f fff BBBBBBB"
HEADER_SIZE = 6

def parse_date_arg(date_str):
    try:
        dt = datetime.strptime(date_str, "%m/%d/%Y|%H:%M:%S")
        return dt.timestamp()
    except Exception as e:
        print(f"Error parsing date '{date_str}': {e}")
        sys.exit(1)

def read_mission_data_filtered(folder_path, min_ts=None, max_ts=None):
    data = {
        'time': [],
        'temps': [[] for _ in range(4)],
        'accel': [[] for _ in range(3)],
        'gyro':  [[] for _ in range(3)],
        'mag':   [[] for _ in range(3)],
        'bme':   [[] for _ in range(3)], 
        'ina':   [[] for _ in range(3)], 
        'mpl':   [], 
        'gps':   [[] for _ in range(3)], 
        'statuses': [[] for _ in range(7)]
    }

    files = sorted(glob.glob(os.path.join(folder_path, "*.ccsds")))
    if not files: return None

    for filepath in files:
        with open(filepath, "rb") as f:
            while True:
                header_data = f.read(HEADER_SIZE)
                if len(header_data) < HEADER_SIZE: break
                header = struct.unpack(">HHH", header_data)
                length = header[2] + 1
                payload = f.read(length)
                if len(payload) < length: break

                try:
                    d = struct.unpack(PAYLOAD_FORMAT, payload)
                    ts = d[0]
                    if min_ts is not None and ts < min_ts: continue
                    if max_ts is not None and ts > max_ts: continue

                    data['time'].append(ts)
                    for i in range(4): data['temps'][i].append(d[1+i])
                    for i in range(3): data['accel'][i].append(d[5+i])
                    for i in range(3): data['gyro'][i].append(d[8+i])
                    for i in range(3): data['mag'][i].append(d[11+i])
                    for i in range(3): data['bme'][i].append(d[14+i])
                    for i in range(3): data['ina'][i].append(d[17+i])
                    data['mpl'].append(d[20])
                    for i in range(3): data['gps'][i].append(d[21+i])
                    for i in range(7): data['statuses'][i].append(d[24+i])
                except struct.error: continue
    return data

def create_window(title, x_timestamps, y_data_list, labels, y_label, mode="local", color_map=None):
    plt.figure(num=title, figsize=(10, 6))
    dates = [datetime.fromtimestamp(ts) for ts in x_timestamps]

    for i, y_data in enumerate(y_data_list):
        color = color_map[i] if color_map else None
        plt.scatter(dates, y_data, label=labels[i], s=3, alpha=0.7, color=color)

    ax = plt.gca()
    ax.xaxis.set_major_locator(mdates.AutoDateLocator())
    ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(ax.xaxis.get_major_locator()))

    plt.title(title)
    plt.ylabel(y_label)
    plt.legend(loc='upper right', markerscale=3)
    plt.grid(True, linestyle=':', alpha=0.4)
    plt.gcf().autofmt_xdate()
    plt.tight_layout()

    filename = title.replace(" ", "_").replace("(", "").replace(")", "").replace("/", "-") + ".png"
    save_path = os.path.join("graphs", filename)
    plt.savefig(save_path)
    
    if mode == "web":
        plt.close() # Close figure to save memory in web mode

def generate_html_gallery(folder="graphs"):
    files = sorted(glob.glob(os.path.join(folder, "*.png")))
    html_content = """<html><head><title>Mission Data</title>
    <style>body{font-family:sans-serif; background:#f0f0f0; text-align:center;}
    .container{margin:20px auto; padding:10px; background:white; border-radius:8px; display:inline-block;}
    img{max-width:90vw; height:auto;}</style>
    <meta http-equiv="refresh" content="30"></head>
    <body><h1>Mission Control Dashboard</h1>"""
    
    for f in files:
        rel_path = os.path.basename(f)
        html_content += f'<div class="container"><h3>{rel_path}</h3><img src="{rel_path}"></div><br>\n'
    
    with open(os.path.join(folder, "index.html"), "w") as f:
        f.write(html_content + "</body></html>")

if __name__ == "__main__":
    target_folder = "data"
    if not os.path.exists("graphs"): os.makedirs("graphs")

    # Default settings
    min_ts, max_ts = None, None
    run_mode = "local" # Default mode

    for arg in sys.argv:
        if arg.startswith("--minDate="): min_ts = parse_date_arg(arg.split("=")[1])
        if arg.startswith("--maxDate="): max_ts = parse_date_arg(arg.split("=")[1])
        if arg == "--web": run_mode = "web"
        if arg == "--local": run_mode = "local"

    mission_data = read_mission_data_filtered(target_folder, min_ts, max_ts)

    if mission_data and mission_data['time']:
        time_data = mission_data['time']
        
        # Plotting calls
        create_window("Temperatures", time_data, mission_data['temps'] + [mission_data['bme'][0]], 
                      [f'T{i+1}' for i in range(4)] + ['BME'], "°C", mode=run_mode)
        create_window("Accelerometer", time_data, mission_data['accel'], ['X', 'Y', 'Z'], "g", mode=run_mode)
        create_window("GPS Altitude", time_data, [mission_data['gps'][2]], ["Altitude"], "m", mode=run_mode)
        create_window("Subsystem Status", time_data, mission_data['statuses'], 
                      ['BME', 'INA', 'IMU', 'Temp', 'MPL', 'GPS', 'RTC'], "0=Fail, 1=OK", mode=run_mode)

        generate_html_gallery("graphs")
        
        if run_mode == "local":
            plt.show()
        else:
            print(f"Web gallery updated at {datetime.now().strftime('%H:%M:%S')}")
    else:
        print("No data found.")